### ISSUE TITLE
如何发布website?

### ISSUE THREAD

**Issue by w3286879** [ziaochina/mk-tools#1]
如何单独发布website？我这边是windows 服务器, 要打开控制台窗口npm start?  不能打包部署到IIS么？
感觉这套框架不错。

**Comment by w3286879** [comment]
找到了 直接 webpack -p 打包出来 用IIS发布。

**Comment by ziaochina** [comment]
好的，不好意思，这几天忙没看问题

**Comment by w3286879** [comment]
没事，这个框架给了我挺多启发的，我发觉Input.TextArea 使用的时候 绑定参数无法输入值。
